### ISSUE TITLE
Length and orientation files

### ISSUE THREAD

**Issue by alannahcb** [DaveHealy-Aberdeen/FracPaQ#7]
Hi All, 

Enjoying using FracPaQ for the first time, thanks for this great tool!  

Any suggestions on how to generate a .txt file for all of the length and orientation data for both traces and segments @DaveHealy-github?
Ideally would have the associated orientations and lengths for each fracture. 
I'd like to generate Fisher distributions and some other specific length statistics from these data. 

Many thanks! 
Alannah

**Comment by DaveHealy-github** [comment]
Hello, and thanks!
ASCII .txt files of orientations and lengths are output to the current folder whenever you run a length or angle plot. e.g., FracPaQ2Dsegmentlengths_Run1.txt. 
These are produced by guiFracPaQ2Dlength.m and guiFracPaQ2Dangle.m; to output a custom file format, you should be able to hack the code in these modules...
All the best 
Dave

**Comment by alannahcb** [comment]
Thanks very much Dave for clarifying that! My mistake, as I'd seen the length file but not realised the first column is the orientation data. That's excellent. I'm using dfnWorks to calculate permeability through 3D flow simulations, so need to use slightly different statistics for inputs. Very happy to have found FracPaQ has saved me sooo much time, thanks again for this!
